const ShopActionTypes = {
    FETCH_ALL_VENDOR_SHOP_START: "FETCH_ALL_VENDOR_SHOP_START",
    FETCH_ALL_VENDOR_SHOP_SUCCESS: "FETCH_ALL_VENDOR_SHOP_SUCCESS",
    FETCH_ALL_VENDOR_SHOP_FAILURE: "FETCH_ALL_VENDOR_SHOP_FAILURE",
    
    FETCH_ALL_SHOP_START: "FETCH_ALL_SHOP_START",
    FETCH_ALL_SHOP_SUCCESS: "FETCH_ALL_SHOP_SUCCESS",
    FETCH_ALL_SHOP_FAILURE: "FETCH_ALL_SHOP_FAILURE",
    
    FETCH_SHOP_CATEGORIES_START: "FETCH_SHOP_CATEGORIES_START",
    FETCH_SHOP_CATEGORIES_SUCCESS: "FETCH_SHOP_CATEGORIES_SUCCESS",
    FETCH_SHOP_CATEGORIES_FAILURE: "FETCH_SHOP_CATEGORIES_FAILURE",
}
export default ShopActionTypes;