const CartActionTypes = {
    TOGGLE_CART_HIDDEN : "TOGGLE_CART_HIDDEN",
    REMOVE_ITEM: "REMOVE_ITEM",
    SUBTRACT_ITEM_QUANTITY: "SUBTRACT_ITEM_QUANTITY",
    CLEAR_ITEMS_FROM_CART: "CLEAR_ITEMS_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
    ADD_ITEMS_TO_CART_START: 'ADD_ITEMS_TO_CART_START',
    ADD_CART_SUCCESS_POPUP: 'ADD_CART_SUCCESS_POPUP',
    CLEAR_CART_SUCCESS_POPUP: 'CLEAR_CART_SUCCESS_POPUP',
    ADD_ITEMS_TO_CART_SUCCESS: 'ADD_ITEMS_TO_CART_SUCCESS',
    ADD_ITEMS_TO_CART_FAILURE: 'ADD_ITEMS_TO_CART_FAILURE',
    CLICKED_CART: 'CLICKED_CART',
}
export default CartActionTypes